from pydantic import BaseModel, Field
from typing import Optional, List
from datetime import datetime, timezone
from src.models.message import Message

has_generated_title_description = (
    "Track if the conversation title has bee generated by the AI"
)


class BaseConversation(BaseModel):
    userId: str = Field(..., description="Unique ID of the user")
    title: str = Field(..., description="Title of the conversation")
    hasGeneratedTitle: bool = Field(
        default=False, description=has_generated_title_description
    )


class Conversation(BaseConversation):
    id: str = Field(..., description="Conversation ID")
    createdAt: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Conversation creation date",
    )
    updatedAt: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Conversation update date",
    )


class ConversationWithMessages(Conversation):
    messages: List[Message] = Field(
        ..., description="List of all conversation messages ordered by timestamp"
    )


class UpdateConversation(BaseModel):
    title: Optional[str] = Field(None, description="New title of the conversation")
    hasGeneratedTitle: Optional[bool] = Field(
        None, description=has_generated_title_description
    )
